# https://travis-ci.org

sudo: required

language: cpp

dist: xenial

addons:
  apt:
    update: true
    packages:
      - ant
      - aria2
      - build-essential
      - cmake
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - pv
      - software-properties-common
    sources:
      - sourceline: 'ppa:zoogie/sdl2-snapshots'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
  homebrew:
    update: true
    packages:
      - ccache
      - python
      - sdl2

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/clcache

matrix:
  include:
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
           APP_ABI=armeabi-v7a
           LIBRETRO=TRUE
           platform=classic_armv8_a35
    - os: linux
      compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux
           APP_ABI=armeabi-v7a
           LIBRETRO=TRUE
           platform=classic_armv7_a7
           
before_install:
  - travis_retry bash .travis.sh travis_before_install

install:
  - travis_retry bash .travis.sh travis_install

script:
  - bash .travis.sh travis_script

after_success:
  - bash .travis.sh travis_after_success
